"""
Database Utility Module
=======================

Centralized database access layer for ForenSight AI.

Responsibilities
----------------
1. Manage database storage locations
2. Provide SQLite connection helpers
3. Execute structured log queries
4. Persist generated detection alerts
5. Maintain consistent runtime database paths

Databases
---------
structured_logs.db
    Stores normalized and parsed log events

alerts.db
    Stores alerts generated by detection engines

Architecture Notes
------------------
• Uses unified runtime storage directory
• Compatible with both .py and packaged .exe execution
• Designed for PyInstaller compatibility
• Prevents duplicate database creation across environments
"""

import os
import sqlite3


# ---------------------------------------------------------
# APPLICATION DATA DIRECTORY
# ---------------------------------------------------------

def get_app_data_dir():
    """
    Return centralized application dataset directory.

    Returns
    -------
    str
        Absolute dataset directory path
    """

    downloads_dir = os.path.join(
        os.path.expanduser("~"),
        "Downloads"
    )

    app_data_dir = os.path.join(
        downloads_dir,
        "ForenSightAI",
        "Dataset"
    )

    os.makedirs(app_data_dir, exist_ok=True)

    return app_data_dir


# ---------------------------------------------------------
# DATABASE PATH HELPERS
# ---------------------------------------------------------

def get_log_db_path():
    """
    Return structured logs database path.

    Returns
    -------
    str
        structured_logs.db path
    """

    return os.path.join(
        get_app_data_dir(),
        "structured_logs.db"
    )


def get_alert_db_path():
    """
    Return alerts database path.

    Returns
    -------
    str
        alerts.db path
    """

    return os.path.join(
        get_app_data_dir(),
        "alerts.db"
    )


# ---------------------------------------------------------
# GLOBAL DATABASE PATHS
# ---------------------------------------------------------

LOG_DB_PATH = get_log_db_path()
ALERT_DB_PATH = get_alert_db_path()


# ---------------------------------------------------------
# DATABASE CONNECTION HELPERS
# ---------------------------------------------------------

def get_log_connection():
    """
    Create connection to structured logs database.

    Returns
    -------
    sqlite3.Connection
    """

    return sqlite3.connect(LOG_DB_PATH)


def get_alert_connection():
    """
    Create connection to alerts database.

    Returns
    -------
    sqlite3.Connection
    """

    return sqlite3.connect(ALERT_DB_PATH)


# ---------------------------------------------------------
# QUERY EXECUTION
# ---------------------------------------------------------

def execute_query(query):
    """
    Execute SQL query against structured logs database.

    Parameters
    ----------
    query : str
        SQL query string

    Returns
    -------
    list
        Query result rows
    """

    conn = get_log_connection()
    cursor = conn.cursor()

    cursor.execute(query)

    rows = cursor.fetchall()

    conn.close()

    return rows


# ---------------------------------------------------------
# ALERT STORAGE
# ---------------------------------------------------------

def insert_alert(alert):
    """
    Insert detection alert into alerts database.

    Parameters
    ----------
    alert : dict
        Alert generated by detection engine
    """

    conn = get_alert_connection()
    cursor = conn.cursor()

    cursor.execute(
        """
        INSERT INTO alerts
        (
            timestamp,
            alert_type,
            source_ip,
            username,
            severity,
            description
        )
        VALUES (?, ?, ?, ?, ?, ?)
        """,
        (
            alert.get("timestamp"),
            alert.get("type"),
            alert.get("source_ip"),
            alert.get("username"),
            alert.get("severity"),
            alert.get("details"),
        )
    )

    conn.commit()
    conn.close()